[package]
name = "dali_tools"
version = "0.1.0"
authors = ["ksb <ksb@fluffware.se>"]
edition = "2018"

[dependencies]
futures = "0.3.1"
futures-locks = "0.5.*"
hidapi = "1.*"
hyper = "0.12.*"
clap = "2.33.*"

[[bin]]
name = "dali_tools"
path = "src/main.rs"

[[bin]]
name = "swap_addr"
path = "src/swap_addr.rs"
